//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not change the role of this user.
        /// </summary>
        public static string AccessDeniedForChangeRole {
            get {
                return ResourceManager.GetString("AccessDeniedForChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add this role to other user!.
        /// </summary>
        public static string AccessDeniedForChangeThisRole {
            get {
                return ResourceManager.GetString("AccessDeniedForChangeThisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AccessModifre not found.
        /// </summary>
        public static string AccessModifireNotFound {
            get {
                return ResourceManager.GetString("AccessModifireNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment not found.
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Content not found.
        /// </summary>
        public static string ContentNotFound {
            get {
                return ResourceManager.GetString("ContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value already exists.
        /// </summary>
        public static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has already been registered.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not have any extension!.
        /// </summary>
        public static string FileDoesNotHaveExtention {
            get {
                return ResourceManager.GetString("FileDoesNotHaveExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site does not support file {0} extension!.
        /// </summary>
        public static string FileExtentionDoesNotSupport {
            get {
                return ResourceManager.GetString("FileExtentionDoesNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} did not uploaded successfully!.
        /// </summary>
        public static string FileNotUploaded {
            get {
                return ResourceManager.GetString("FileNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify any file for uploading!.
        /// </summary>
        public static string FileNull {
            get {
                return ResourceManager.GetString("FileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Id structure is invalid.
        /// </summary>
        public static string InvalidContentIdStructure {
            get {
                return ResourceManager.GetString("InvalidContentIdStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid direction value , correct value : rtl or ltr.
        /// </summary>
        public static string InvalidDirectionValue {
            get {
                return ResourceManager.GetString("InvalidDirectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email structure is invalid.
        /// </summary>
        public static string InvalidEmailStructure {
            get {
                return ResourceManager.GetString("InvalidEmailStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation token invalid signiture.
        /// </summary>
        public static string InvalidJwtToken {
            get {
                return ResourceManager.GetString("InvalidJwtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question count must between 1 and 100.
        /// </summary>
        public static string InvalidQuestionCountValue {
            get {
                return ResourceManager.GetString("InvalidQuestionCountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is invalid.
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleId value is invalid.
        /// </summary>
        public static string InvalidRoleId {
            get {
                return ResourceManager.GetString("InvalidRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserName and/or Password.
        /// </summary>
        public static string InvalidUserAndOrPass {
            get {
                return ResourceManager.GetString("InvalidUserAndOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verb tense id must between 1 and 17.
        /// </summary>
        public static string InvalidVerbTenseValue {
            get {
                return ResourceManager.GetString("InvalidVerbTenseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You passing verb tense but your word type is not verb!.
        /// </summary>
        public static string InvalidWordTypeStructure {
            get {
                return ResourceManager.GetString("InvalidWordTypeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word type id must between 1 and 6.
        /// </summary>
        public static string InvalidWordTypeValue {
            get {
                return ResourceManager.GetString("InvalidWordTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lable in content not found.
        /// </summary>
        public static string LableInContentNotFound {
            get {
                return ResourceManager.GetString("LableInContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lable not found.
        /// </summary>
        public static string LableNotFound {
            get {
                return ResourceManager.GetString("LableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must not be null or empty.
        /// </summary>
        public static string MostNotBeNull {
            get {
                return ResourceManager.GetString("MostNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} in {1} must not be null or empty.
        /// </summary>
        public static string MostNotBeNullWithIn {
            get {
                return ResourceManager.GetString("MostNotBeNullWithIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of words is not enough to make an answer.
        /// </summary>
        public static string NotEnoughAnswers {
            get {
                return ResourceManager.GetString("NotEnoughAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification not found.
        /// </summary>
        public static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notifications list is empty.
        /// </summary>
        public static string NotificationsListEmpty {
            get {
                return ResourceManager.GetString("NotificationsListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is not active!.
        /// </summary>
        public static string RefreshTokenIsNotActive {
            get {
                return ResourceManager.GetString("RefreshTokenIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related contents not found.
        /// </summary>
        public static string RelatedContentsNotFound {
            get {
                return ResourceManager.GetString("RelatedContentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role not found.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred.
        /// </summary>
        public static string UnkonwnError {
            get {
                return ResourceManager.GetString("UnkonwnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been blocked please contact support.
        /// </summary>
        public static string UserBanned {
            get {
                return ResourceManager.GetString("UserBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The users list is empty.
        /// </summary>
        public static string UserListEmpty {
            get {
                return ResourceManager.GetString("UserListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username has already been registered.
        /// </summary>
        public static string UserNameExist {
            get {
                return ResourceManager.GetString("UserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word not found.
        /// </summary>
        public static string WordNotFound {
            get {
                return ResourceManager.GetString("WordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word: {0} in {1} not found.
        /// </summary>
        public static string WordNotFoundWithIn {
            get {
                return ResourceManager.GetString("WordNotFoundWithIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words list is empty.
        /// </summary>
        public static string WordsListEmpty {
            get {
                return ResourceManager.GetString("WordsListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} for {1} property is wrong.
        /// </summary>
        public static string WrongValue {
            get {
                return ResourceManager.GetString("WrongValue", resourceCulture);
            }
        }
    }
}
